import { useEffect, useRef, useState } from "react";
import { ArrowSquareOut, Clock, MapPin, Package, PencilSimple, X } from "@phosphor-icons/react";
import { formatMtuDate, MTU_KHS_DRAWING_FOLDERS, MTU_KHS_LIFECYCLE_LABEL, MTU_KHS_RECONCILIATION_STATUS, MTU_KHS_RECONCILIATION_LABEL, sameYearDrawing, validateMtuStockReference } from "./mtuKhsModel.js";

const value = item => item == null || item === "" ? "-" : String(item);
const importantDates = record => [["Tanggal kontrak", record.tanggalKontrak], ["Delivery / BASTB", record.tanggalSerahTerima], ["Material onsite", record.onsiteDate], ["Rencana pasang", record.installationPlanDate], ["Realisasi pasang", record.installationDate || record.tanggalTerpasang]].filter(([, item]) => item);

export function MtuKhsDetail({ record, documents = [], usage = [], canEdit = false, canRegisterDocument = false, canLinkUsage = false, onClose, onSubmit, onRegisterDocument, onLinkUsage, approvedTugItems = [], stockCandidates = [], stockLinks = [], canReconcile = false, onSaveReconciliation, onLinkStock, receiptSummary, receipts = [], canCreateReceipt = false, onCreateReceipt, C, sty }) {
  const [activeTab, setActiveTab] = useState("summary");
  const closeRef = useRef(null);
  const [documentDraft, setDocumentDraft] = useState({ title: "", url: "", revision: "" });
  const [usageDraft, setUsageDraft] = useState({ id: "", qty: "" });
  const [stockDraft, setStockDraft] = useState({ id: "", qty: "" });
  const isPhysical = record.sifatPekerjaan !== "SUPERVISI";
  const year = Number(record.procurementYear);
  const reconciliation = record.reconciliationStatus || record.reconciliation_status || "BELUM_DICEK";
  const receiptQty = Number(receiptSummary?.receivedQty ?? receiptSummary?.received_qty ?? record.receivedQty ?? record.received_qty ?? receipts.reduce((sum, item) => sum + (Number(item.qty) || 0), 0)) || 0;
  const remainingReceipt = Math.max(0, Number(record.qty || 0) - receiptQty);
  useEffect(() => {
    closeRef.current?.focus();
    const onKeyDown = event => { if (event.key === "Escape") onClose?.(); };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [record?.id]);
  if (!record) return null;
  const drawings = documents.filter(document => sameYearDrawing(record, document));
  const usedQty = usage.reduce((total, item) => total + (Number(item.qty || item.quantity) || 0), 0);
  const detailRows = [
    ["Vendor", record.vendor], ["Kode RFQ", record.mtuCode], ["Material", record.materialName], ["Deskripsi katalog", record.materialDescription], ["Code Catalog", record.catalogNumber], ["Jenis katalog", record.catalogType], ["Qty", `${record.qty || 0} ${record.unit || "unit"}`], ["Terpasang", `${record.installedQty ?? 0} ${record.unit || "unit"}`], ["Sisa", `${record.remainingQty ?? record.physicalQty ?? 0} ${record.unit || "unit"}`],
    ["Kontrak KHS", record.noKontrak], ["Kontrak rinci", record.contractDetailNumber || record.noKontrak], ["SPMK", record.noSpmk],
  ];
  const dates = importantDates(record);
  return <div className="mtu-khs-detail-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}>
    <section className="mtu-khs-detail" role="dialog" aria-modal="true" aria-labelledby="mtu-khs-detail-title">
      <header className="mtu-khs-detail__header">
        <div><span className="mtu-khs-eyebrow">MTU KHS {record.procurementYear || ""}</span><h2 id="mtu-khs-detail-title">{value(record.materialDescription || record.materialName || record.mtuCode)}</h2><p>{value(record.mtuCode)} · {value(record.vendor)} · {value(record.uptName)}</p></div>
        <button ref={closeRef} type="button" className="mtu-khs-icon-button" aria-label="Tutup detail" onClick={onClose}><X size={20} /></button>
      </header>
      <div className="mtu-khs-detail__status"><span className="mtu-khs-detail__meta">Status: {MTU_KHS_LIFECYCLE_LABEL[record.lifecycleStatus] || record.lifecycleStatus}</span><span className="mtu-khs-detail__meta">Jenis: {record.sifatPekerjaan}</span></div>
      <div className="mtu-khs-detail__tabs" role="tablist">{[["summary","Ringkasan"],["location","Lokasi"],["usage","Pengeluaran TUG-8/9"],["installation","Pemasangan"],["history","Riwayat"]].map(([key, label]) => <button key={key} type="button" role="tab" aria-selected={activeTab === key} className={activeTab === key ? "is-active" : ""} onClick={() => setActiveTab(key)}>{label}</button>)}</div>
      <div className="mtu-khs-detail__body">
        {activeTab === "summary" && <><div className="mtu-khs-detail-grid mtu-khs-detail-grid--compact">{detailRows.map(([label, item]) => <div key={label}><span>{label}</span><strong title={String(item || "")}>{value(item)}</strong></div>)}</div>{dates.length > 0 && <div className="mtu-khs-detail__section mtu-khs-detail__section--compact"><h3><Clock size={17} /> Tanggal penting</h3><div className="mtu-khs-important-dates">{dates.map(([label, date]) => <div key={label}><span>{label}</span><time dateTime={String(date).slice(0, 10)}>{formatMtuDate(date)}</time></div>)}</div></div>}</>}
        {activeTab === "location" && <div className="mtu-khs-detail__section"><h3><MapPin size={17} /> Jejak lokasi</h3><p className="mtu-khs-muted">UPT {value(record.uptName)} · ULTG {value(record.ultgName)}</p><p><strong>{value(record.giName)}</strong> / {value(record.bayName)} · {value(record.location)}</p><div className="mtu-khs-timeline"><div><span className="is-done" /><p><strong>Vendor / Pabrik</strong><small>{value(record.tanggalFAT || record.fatDate)}</small></p></div><div><span className={record.onsiteDate ? "is-done" : ""} /><p><strong>Onsite GI</strong><small>{value(record.onsiteDate || record.tanggalOnsite)}</small></p></div><div><span className={record.installationDate ? "is-done" : ""} /><p><strong>Terpasang</strong><small>{value(record.installationDate || record.tanggalTerpasang)}</small></p></div></div></div>}
        {activeTab === "usage" && <div className="mtu-khs-detail__section"><h3><Package size={17} /> Pengeluaran TUG-8/9 approved</h3><div className="mtu-khs-usage-summary"><strong>{usedQty}</strong><span>dari {record.qty || 0} {record.unit || "unit"} terhubung ke TUG final</span></div>{usage.length === 0 && <p className="mtu-khs-muted">Belum ada TUG-8/9 final yang terhubung.</p>}{usage.map(item => <p key={item.id}><strong>{item.docNumber || item.doc_number || item.tugItemId || item.tug_item_id}</strong> · {item.docType || item.doc_type || "TUG"} · {formatMtuDate(item.finalApprovedAt || item.final_approved_at)} · {item.materialName || item.catalogNumber || "Material"} · {item.qty || item.quantity} {record.unit || "unit"}</p>)}{canLinkUsage && approvedTugItems.length > 0 && <div className="mtu-khs-usage-link"><select aria-label="TUG approved" value={usageDraft.id} onChange={event => setUsageDraft(draft => ({ ...draft, id: event.target.value }))}><option value="">Pilih TUG approved</option>{approvedTugItems.filter(item => String(item.uptId) === String(record.uptId) && (!record.katalogId || String(item.katalogId) === String(record.katalogId))).map(item => <option key={item.id} value={item.id}>{item.docNumber} · {item.docType} · {item.qty}</option>)}</select><input aria-label="Qty pemakaian" type="number" min="0.01" step="0.01" placeholder="Qty" value={usageDraft.qty} onChange={event => setUsageDraft(draft => ({ ...draft, qty: event.target.value }))} /><button type="button" className="approval-btn approval-btn--primary" onClick={() => { if (usageDraft.id && usageDraft.qty) onLinkUsage?.(record.id, usageDraft.id, Number(usageDraft.qty)); }}>Link TUG</button></div>}</div>}
        {activeTab === "usage" && isPhysical && year === 2024 && <div className="mtu-khs-detail__section mtu-khs-reconciliation"><h3>Rekonsiliasi TUG 2024</h3><p className="mtu-khs-muted">Keterangan TL untuk status proses TUG. Tidak mengubah qty stok.</p><select aria-label="Status rekonsiliasi TUG" disabled={!canReconcile} value={reconciliation} onChange={event => onSaveReconciliation?.(record.id, event.target.value)}>{MTU_KHS_RECONCILIATION_STATUS.map(status => <option key={status} value={status}>{MTU_KHS_RECONCILIATION_LABEL?.[status] || status}</option>)}</select>{(record.reconciliationActor || record.reconciliation_actor) && <small>Diubah oleh {record.reconciliationActor || record.reconciliation_actor} · {formatMtuDate(record.reconciliationAt || record.reconciliation_at)}</small>}{stockLinks.map(item => <p key={item.id}><strong>Stok {item.stock_id || item.stockId}</strong> · referensi {item.qty} {record.unit || "unit"}</p>)}{canReconcile && <><p className="mtu-khs-muted">Referensi Data Stok (opsional): hanya UPT dan katalog sama.</p><select aria-label="Data Stok MTU" disabled={!record.katalogId} value={stockDraft.id} onChange={event => setStockDraft(draft => ({ ...draft, id: event.target.value }))}><option value="">Pilih Data Stok</option>{stockCandidates.filter(stock => validateMtuStockReference(record, stock).valid).map(stock => <option key={stock.id} value={stock.id}>{stock.namaBarang || stock.name || stock.id} · {stock.qty ?? stock.quantity ?? 0}</option>)}</select><input aria-label="Qty referensi stok" type="number" min="0.01" step="0.01" disabled={!record.katalogId} value={stockDraft.qty} onChange={event => setStockDraft(draft => ({ ...draft, qty: event.target.value }))} /><button type="button" className="approval-btn approval-btn--secondary" disabled={!record.katalogId || !stockDraft.id || !stockDraft.qty} onClick={() => onLinkStock?.(record.id, stockDraft.id, Number(stockDraft.qty))}>Tautkan stok</button>{!record.katalogId && <p className="mtu-khs-muted">Katalog belum dipetakan; penautan stok belum tersedia.</p>}</>}</div>}
        {isPhysical && year === 2026 && <div className="mtu-khs-detail__section mtu-khs-reconciliation"><h3>Penerimaan Material TUG-3/4</h3><p>Selesai diterima: <strong>{receiptQty}</strong> · Sisa: <strong>{remainingReceipt}</strong> {record.unit || "unit"}</p>{receipts.map(item => <p key={item.id}>{item.docNumber || item.doc_number || item.id} · {item.qty} · {item.status || "-"}</p>)}{canCreateReceipt && <button type="button" className="approval-btn approval-btn--primary" disabled={!record.katalogId || remainingReceipt <= 0} title={!record.katalogId ? "Petakan katalog terlebih dahulu" : remainingReceipt <= 0 ? "Qty sudah diterima seluruhnya" : ""} onClick={() => onCreateReceipt?.(record)}>Buat Draft TUG-3</button>}{!record.katalogId && <p className="mtu-khs-muted">Katalog belum dipetakan, draft TUG-3 belum bisa dibuat.</p>}</div>}
        {activeTab === "installation" && <div className="mtu-khs-detail__section"><h3><MapPin size={17} /> Pemasangan</h3><div className="mtu-khs-detail-grid"><div><span>Status</span><strong>{value(record.installationStatus || record.lifecycleStatus)}</strong></div><div><span>Rencana</span><strong>{value(record.installationPlanDate)}</strong></div><div><span>Aktual</span><strong>{value(record.installationDate || record.tanggalTerpasang)}</strong></div></div></div>}
        {activeTab === "history" && <div className="mtu-khs-detail__section"><h3><Clock size={17} /> Riwayat perubahan</h3><p className="mtu-khs-muted">Riwayat approval akan tampil setelah change request MTU tersedia.</p></div>}
        {activeTab === "summary" && <div className="mtu-khs-detail__section"><h3><Clock size={17} /> Drawing tahun yang sama</h3>{drawings.length ? <div className="mtu-khs-doc-list">{drawings.map(document => <a key={document.id || document.url} href={document.url} target="_blank" rel="noreferrer"><span>{document.title || document.documentType}</span><ArrowSquareOut size={16} /></a>)}</div> : <p className="mtu-khs-muted">Drawing exact PDF belum tersedia. Dokumen tahun lain tidak ditampilkan.</p>}{MTU_KHS_DRAWING_FOLDERS[record.vendor?.toUpperCase()] && <a className="mtu-khs-folder-link" href={MTU_KHS_DRAWING_FOLDERS[record.vendor.toUpperCase()]} target="_blank" rel="noreferrer">Sumber folder vendor (navigasi saja) <ArrowSquareOut size={15} /></a>}{canRegisterDocument && <div className="mtu-khs-doc-form"><input aria-label="Judul drawing" placeholder="Judul PDF" value={documentDraft.title} onChange={event => setDocumentDraft(draft => ({ ...draft, title: event.target.value }))} /><input aria-label="URL drawing" type="url" placeholder="https://.../file.pdf" value={documentDraft.url} onChange={event => setDocumentDraft(draft => ({ ...draft, url: event.target.value }))} /><input aria-label="Revisi drawing" placeholder="Revisi" value={documentDraft.revision} onChange={event => setDocumentDraft(draft => ({ ...draft, revision: event.target.value }))} /><button type="button" className="approval-btn approval-btn--secondary" onClick={() => { if (documentDraft.title && documentDraft.url) onRegisterDocument?.(record.id, documentDraft); }}>Tambahkan PDF exact</button></div>}</div>}
      </div>
      {canEdit && <footer className="mtu-khs-detail__footer"><button type="button" className="approval-btn approval-btn--primary" onClick={() => onSubmit?.(record)}><PencilSimple size={17} /> Ajukan perubahan</button></footer>}
    </section>
  </div>;
}
